import { createApp } from 'vue';
import App from './App.vue';
import router from './router';
import store from './store';
import ElementPlus from 'element-plus';
import 'element-plus/dist/index.css';
import VueParticles from 'vue-particles';
import { createPinia } from 'pinia';
import './icons';
const app = createApp(App);
app.use(createPinia());
app.use(ElementPlus);
app.use(VueParticles);
app.use(store).use(router).mount('#app');
